apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: awx
spec:
  host: ec2-13-200-111-209.ap-south-1.compute.amazonaws.com
  tls:
    secret: tls-cert
  upstreams:
  - name: ansible-awx-service
    service: ansible-awx-service
    port: 80
    lb-method: round_robin # Load balancing Algo to use 
    max-conns: 5 #Controlling 5 max concurrent connection per second
  routes:
  - path: /
    action:
      pass: ansible-awx-service

