        apiVersion: v1
        kind: Secret
        metadata:
          name: argocd-vault-plugin-credentials
          namespace: argocd # Or your ArgoCD namespace
        type: Opaque
        stringData:
          AVP_TYPE: "AppRole"
          VAULT_ADDR: "https://ec2-13-200-111-209.ap-south-1.compute.amazonaws.com:32067"
          VAULT_ROLE_ID: "default"
          VAULT_SECRET_ID: "root"
